### ISSUE TITLE
Add markdown tables with some html and styling as in xlsform.org to the support articles

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/docs#124]
We would love to figure out how to replicate the excel-like tables used in xlsform.org and incorporate them to our support articles.

![image](https://user-images.githubusercontent.com/22472326/135485055-a6522f32-3ff2-4a86-acdc-47fcb198cd81.png)

They seem to be using just markdown with some extra styling in the bottom tabs ([see here](https://github.com/XLSForm/xlsform.github.io/blob/master/_sections/home-english.md?plain=1#L310))

This is primarily for @magicznyleszek to figure out how to replicate them, but once this is an option maybe @Kalyan-Lama and @joshuaberetta can determine in which articles we could use these tables.

**Comment by joshuaberetta** [comment]
A nice list of support articles containing tables is here: https://github.com/kobotoolbox/docs/issues/96

**Comment by magicznyleszek** [comment]
From a little investigation, this seems to be happening:

Documents use markdown tables with a footer containing active sheet name (here it's `choices`):

```markdown
| list_name           | name        | label                |
| ------------------- | ----------- | -------------------- |
| gender              | transgender | Transgender          |
| gender              | female      | Female               |
| gender              | male        | Male                 |
| gender              | other       | Other                |
| =================== | ========    | ==================== |
| choices             |             |                      |
```

There is a function `addSheets` in https://github.com/XLSForm/xlsform.github.io/blob/master/assets/js/script.js#L134 that runs when document is loaded and sets the nice footer. Plus some nice styles in https://github.com/XLSForm/xlsform.github.io/blob/master/assets/css/main.css#L54
