### ISSUE TITLE
Update support article "Manually Uploading Submissions"!

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#125]
This article may need to be updated, especially on accessing the folders within the android phone. This change is a result of the most recent security updates on how android stores files.

Additional: 

Check out this path (to see if it works)

This PC\Device_Model (this may vary)\Phone\Android\data\org.koboc.collect.android\files\projects

**Comment by Ig-Rebollo** [comment]
@StephaneAloo what is the status of this update? Do you need help with it?

**Comment by StephaneAloo** [comment]
Link to the revised article https://docs.google.com/document/d/1rkvZti1qv1H0y13c8gCckYOVtHHF11BYHWz1ZzCXe6M/edit?usp=sharing
@Kalyan-Lama

**Comment by Kalyan-Lama** [comment]
Thank you @StephaneAloo. I reviewed it and it is perfect for me.

**Comment by StephaneAloo** [comment]
I have reviewed this again, and it is ready for copy editing.

**Comment by zoereinecke** [comment]
Reviewed!
