### ISSUE TITLE
Improved article for adding Images, Videos, Audio (and other files) to a Form

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/docs#131]
After the quick fix from #83, this issue is meant to track the progress of a more detailed article explaining how to add not only images but also videos, audio, etc.

This may also be the first article to incorporate a video explanation.

**Comment by Ig-Rebollo** [comment]
@Kalyan-Lama created this new issue for the larger project of creating a better article encompassing all media types. Feel free to post here the link as soon as you have a draft for it. Thanks a lot!

**Comment by Kalyan-Lama** [comment]
@Ig-Rebollo, @joshuaberetta, @StephaneAloo, @c6reid the draft version of the support article is here:

https://docs.google.com/document/d/16H_vmXfrLpdWgSjqtQ4sj1VnN4MQMAD3/edit?usp=sharing&ouid=112352020379718229164&rtpof=true&sd=true

The video and screenshots used in the article can be accessed here:

https://drive.google.com/drive/folders/1BxAZe04d_uMQtGJm0kOOIoo3pi5Oeogu?usp=sharing

**Zulip:** https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Support.20Article.3A.20Adding.20Various.20Types.20of.20Media.20.28Image.2C.20Audio

**Comment by Kalyan-Lama** [comment]
@Ig-Rebollo, @StephaneAloo, @exprin, @h-tawfik please feel free to review, commend and make edits. cc: @joshuaberetta

**Comment by Kalyan-Lama** [comment]
Thank you @exprin for providing a wonderful review :heart: @Ig-Rebollo forwarding it for your review so that we could pass it out to Caitlin.

**Comment by c6reid** [comment]
Just checking in if this is ready for my review @Kalyan-Lama @Ig-Rebollo ? No rush, jsut want to make sure I am not behind on anything.
