### ISSUE TITLE
Update Support Article: Recording Entire Interview with Background Recording

### ISSUE THREAD

**Issue by StephaneAloo** [kobotoolbox/docs#156]
The current article https://support.kobotoolbox.org/recording-interviews.html was written before the development of the future on recording background audio. 

This issue raises the need to update or replace the original article to cover the new future. There is m[aterial from the community forum](https://community.kobotoolbox.org/t/background-audio-recording/17470/13?u=stephanealoo) and the original announcement by ODK that can be found [here](https://forum.getodk.org/t/create-automatic-background-recording-of-interview-in-collect/18601/20?u=stephanealoo).

**Comment by StephaneAloo** [comment]
@Ig-Rebollo @joshuaberetta @Kalyan-Lama I have since created the support article, which you can review [here](https://docs.google.com/document/d/1P8PnkHPRnWJTRxbu1SR9EOZBtOtrKCYh/edit?usp=sharing&ouid=108217224409947108633&rtpof=true&sd=true)

**Comment by Kalyan-Lama** [comment]
Xref: https://github.com/kobotoolbox/docs/issues/85

Closing my issue to avoid confusion here.

**Comment by Ig-Rebollo** [comment]
@StephaneAloo we're incorporating your document into the article @Kalyan-Lama has been working on. There were also duplication in the issues but we will keep this one as the reference. 

**The links to the final article to review are these:**
- Article link: https://docs.google.com/document/d/1iHm8Gm-7OI3J-_DIrvHOlrtRhbiYh7ka/edit?usp=sharing&rtpof=true&sd=true
- Media files link: https://drive.google.com/drive/folders/1NHFRXO667Q_ga7Jj-o-FQl6Fq15U3hfO?usp=sharing

Please @StephaneAloo can you go through these links and make sure we didn't loose any relevant information from your document? I think @Kalyan-Lama made a good job including everything, but if leave comments if you feel anything is missing from your end.

**Comment by StephaneAloo** [comment]
@Ig-Rebollo and @Kalyan-Lama I have gone through the document and it covers everything. There are some pending comments though from @exprin on the document that need to be accepted.

**Comment by Kalyan-Lama** [comment]
Thank you @exprin for providing a wonderful review ❤️ @Ig-Rebollo forwarding it for your review so that we could pass it out to Caitlin.

**Comment by exprin** [comment]
You are welcome @Kalyan-Lama

**Comment by c6reid** [comment]
Checking in here if the article is ready for my review @Ig-Rebollo @Kalyan-Lama ?

**Comment by Ig-Rebollo** [comment]
@Kalyan-Lama I left a couple comments in the article for you to review.

I also noticed the title is a bit different from the equivalent article in the list @exprin made. Alex could you go through this article again and make sure it aligns with the content that is planned for in the spreadsheet list?

Maybe both of you can coordinate to do one last round of edits/review and once you are happy with the result, let @c6reid know by assigning the issue to her.

**Comment by Kalyan-Lama** [comment]
@Ig-Rebollo, I have reviewed the comments. Feel free to add if there is still anything missing. @exprin, could you give it a final scan? Maybe we could then have a quick call to address if there is anything you would like to add/remove from the article. Once done, we could push it to Caitlin for the final review.

**Comment by exprin** [comment]
@Kalyan-Lama, I have gone through it and made very few edit suggestions. Otherwise I think this is good to move to Caitlin

**Comment by c6reid** [comment]
Okay, I can review this today/tomorrow if it's ready for me @Kalyan-Lama @exprin ?

**Comment by Kalyan-Lama** [comment]
Sure @c6reid. It's ready from our side.

**Comment by c6reid** [comment]
@Ig-Rebollo @Kalyan-Lama @joshuaberetta @exprin done reviewing the article, nice work everyone! Kalyan, I only made a few edits using "suggesting" when I wasn't sure if the changes I made were accurate, so hoping you or Josh can quickly review those and make sure it's still correct. Otherwise, it's good to go from my point of view.

**Comment by joshuaberetta** [comment]
Thanks @c6reid!

**Comment by Kalyan-Lama** [comment]
Thank you @c6reid it's perfect. ❤️
