### ISSUE TITLE
Create new support article "Merging Repeat Group Data With Excel"

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#157]
When a user has repeat group questions in the survey form the repeat group data gets downloaded in a different sheet while downloading the data in XLS format. Currently, KoBoToolbox does not support the feature of merging the such data within the system. Hence the objective of this article would be to illustrate how to merge the repeat group data with the main data (those not repeated) in MS Excel.

There are different approaches to merge the dataset. Users could use third-party software such as SPSS, STATA, R, etc. However, this article focuses on using MS Excel as the same should be available on all PCs and does not require the skill to use SPSS, STATA, R, etc.

**Comment by Kalyan-Lama** [comment]
Hi @exprin, would you mind reviewing the first draft of my article? The article can be assessed here:

https://docs.google.com/document/d/15tNcjWDiKIJXkEyYyjWzn5q-9bLEUnje/edit?usp=sharing&ouid=112352020379718229164&rtpof=true&sd=true

The videos can be assessed here:

https://drive.google.com/drive/folders/1jsY9Aaqg7x2bTB4VsuAD8f6kBCnnveMf?usp=sharing

**Comment by Kalyan-Lama** [comment]
Thank you @exprin for reviewing it. @c6reid waiting for your final review and approval.

**Comment by c6reid** [comment]
@Kalyan-Lama I have reviewed and overall it looks pretty good. Left a few questions/comments for you but should be good to go.

**Comment by Kalyan-Lama** [comment]
Thank you @c6reid for reviewing the article.
