### ISSUE TITLE
Update the SPSS article to incorporate new features

### ISSUE THREAD

**Issue by StephaneAloo** [kobotoolbox/docs#159]
We have had some forum discussions that provide alternative approaches towards processing our data for SPSS. There is a need to update the article to cover this particular topic.

https://support.kobotoolbox.org/converting_to_spss_and_stata.html

**Comment by Ig-Rebollo** [comment]
Google doc here: https://docs.google.com/document/d/1XNu18m9tX3CqBwcbW1bbVhst2BzbPp0LWkepPPBg778/edit

**Comment by StephaneAloo** [comment]
@exprin this article is now ready for your review. However, I had pushed a git request as part of the training by @joshuaberetta

**Comment by exprin** [comment]
Thanks @StephaneAloo. I will be going through it just now
