### ISSUE TITLE
New article: What is KoboToolbox

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/docs#168]
Provides background information about Kobotoolbox.
https://docs.google.com/document/d/1X0kDUO5Nj95Fshj3SZCIWEtHaMtQKGVeAUs_Do0F5Vw/edit?usp=sharing

**Comment by exprin** [comment]
@Ig-Rebollo, I have addressed you and @tinok comments on removing mention of Kobocat and splitting KPI into the several components it is made up of (Data management, Library and Project management, of course apart from formbuilder.) @StephaneAloo, I have addressed your comment on adding some visuals. 

Woud you please go through the article maybe one last time before I can submit it to @joshuaberetta?

cc @maedelange
