### ISSUE TITLE
New article: The KoBo Toolbox interface

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#169]
Describes the basic elements of the KoBoToolbox interface.

https://docs.google.com/document/d/1g6lSnSRV5ryT0zvEh7NbdAlozbBaVxnJcLPPhDlek8E/edit?usp=sharing

**Comment by Kalyan-Lama** [comment]
**Link to the article:** https://docs.google.com/document/d/1g6lSnSRV5ryT0zvEh7NbdAlozbBaVxnJcLPPhDlek8E/edit

**Zulip:** https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Support.20Article.3A.20The.20KoBoToolbox.20Interface
