### ISSUE TITLE
New article: Creating an account on Kobotoolbox

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#170]
This article outlines the steps for creating an account in KoBoToolbox and logging back in,
https://docs.google.com/document/d/17ziz4OBEnkAy74g9DJq4lSJeB9QbgZ39LxrwtiNtWAk/edit

**Comment by Kalyan-Lama** [comment]
Link to the article: https://docs.google.com/document/d/17ziz4OBEnkAy74g9DJq4lSJeB9QbgZ39LxrwtiNtWAk/edit
