### ISSUE TITLE
New article: Overview of creating a project in KoBoToolbox

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#174]
This article provides a quick overview of how to create a data collection project, add questions, and deploy it for data entry. This should be a gentle introduction to developing and deploying forms in Kobotoolbox, after which users can go through the rest of the articles in the support site to learn in depth about the steps provided in this article. The idea of the article is to provide a quick win for beginners

https://docs.google.com/document/d/1TzlGREhOrxVAlke2zyLuwHF8rqJ-duOpje0xf0mjeDM/edit?usp=sharing

**Comment by exprin** [comment]
II have completed creating this article, @Ig-Rebollo kindly review it for me.

**Comment by Ig-Rebollo** [comment]
Left some comments in the Google document @exprin, let me know what you think. Once everything is resolved, please let @maedelange know so she can do the final review.
