### ISSUE TITLE
Update article: Resetting passwords

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#179]
Add some more content and structure to the article: https://docs.google.com/document/d/1C0sekGn0hV8fmzpEx0UwbyJMwHZT-iXmifCqA-S8QqE/edit?usp=sharing

Original article: https://support.kobotoolbox.org/reset_password.html

**Comment by StephaneAloo** [comment]
I have since reviewed the article @exprin and it should be ready for your finalization on the same google doc

**Comment by exprin** [comment]
Thanks for the work Stephane

**Comment by Ig-Rebollo** [comment]
@maedelange this article only needs a minor change to the image, but the text is ready for you to review whenever you can.

**Comment by maedelange** [comment]
@Ig-Rebollo @exprin I've suggested a few changes to the text and left a few comments with questions - feel free to reach out if you want to discuss

**Comment by exprin** [comment]
@Ig-Rebollo, @maedelange, is this ready so I can push to @joshuaberetta?

**Comment by maedelange** [comment]
@exprin reviewed! I just changed "KoBoToolbox" to "KoboToolbox"

**Comment by exprin** [comment]
Awesome @maedelange . I have now submitted it to Josh for his final review and publishing. Thanks so much
