### ISSUE TITLE
Minor update to "Creating a new form"

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#183]
Minor edits to the article "Creating a new form". https://docs.google.com/document/d/1J51malnf-LAeYgMX8t0porjkL6kX5y7w_W-dczolCoo/edit?usp=sharing

**Comment by exprin** [comment]
@Kalyan-Lama , I added a few edits to this article. Could you look at it one last time and then we can pass it to Mae-Lin?

**Comment by Kalyan-Lama** [comment]
@exprin, reviewed! Feel free to reach me back if still needed.

**Comment by exprin** [comment]
@maedelange, @Ig-Rebollo, kindly review this article. I just made some minor edits to the existing one.

**Comment by maedelange** [comment]
@exprin reviewed!
