### ISSUE TITLE
New Article: Getting started with XLSForm

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#186]
Introduces users to XLSForm from setting up a basic XLSForm document to uploading it and previewing in KoBoToolbox; and downloading XLSFOrm from KoBoToolbox

https://docs.google.com/document/d/140itRljV8mOo5w4l90LPGc_LBu7T0ktkM6zRUICc0PE/edit?usp=drivesdk

**Comment by maedelange** [comment]
@exprin would you mind adding a Google Docs link when this article is ready for copyediting so I can review? Thanks!

**Comment by maedelange** [comment]
Added my edits - feel free to reach out if you have any questions or would like to discuss further @exprin

**Comment by exprin** [comment]
Wow that was fast! Thanks a lot @maedelange. (:

**Comment by maedelange** [comment]
@exprin reviewed - great video by the way, very easy to follow and understand! I added one more question regarding formatting
