### ISSUE TITLE
Update the matrix question support article (with w10 limitations)

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#19]
As of now the current `Enketo` features restricts the matrix question with a total of `10 columns` which should be updated in the support article.

**Note:** However the number of columns might be increase-able. A GitHub issue has been created for the same which can be followed here:

https://github.com/enketo/enketo-express/issues/208

**Comment by magicznyleszek** [comment]
Added a note to the https://support.kobotoolbox.org/matrix_response.html :)
