### ISSUE TITLE
New Article: Transferring forms and data manually from one android device to another

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#201]
This is a new article that should allow users to transfer forms and data manually from one android device to another.

**Comment by Kalyan-Lama** [comment]
Hi, @exprin would you mind going through this new article? Here is the link to the same:

https://docs.google.com/document/d/1MXT21kIIzP1PvOVVni3VBfQEAwGsfzho/edit?usp=sharing&ouid=112352020379718229164&rtpof=true&sd=true

**Comment by Kalyan-Lama** [comment]
@exprin @StephaneAloo @Ig-Rebollo @joshuaberetta, I intend to place this article under the `Data Collection` section as shown in the image below:

![Image 1](https://user-images.githubusercontent.com/50188479/152521849-24ec068c-37a1-4f4b-b23d-b0ffa294c984.png)
 
i.e. below the article `Data Collection on KoBoCollect App (Older Version)` and above the article `Recommended Devices for Data Collection`.

What would you say? 💭 🤔

**Comment by exprin** [comment]
> Hi, @exprin would you mind going through this new article? Here is the link to the same:
> 
> https://docs.google.com/document/d/1MXT21kIIzP1PvOVVni3VBfQEAwGsfzho/edit?usp=sharing&ouid=112352020379718229164&rtpof=true&sd=true

I will on it right Away @Kalyan-Lama .thanks

**Comment by exprin** [comment]
Hi @Kalyan-Lama ,

I have added my comments and suggestions in this article.
Please let me know after you have worked on it so I can go through one more time.
Cheers

**Comment by Kalyan-Lama** [comment]
Thank you @exprin for the quick review and comments. I have accepted almost all and have left some of mine comments too. Small help needed for your first comment. Could you review them again so that we could push it forward? TIA

**Comment by exprin** [comment]
Hi @Kalyan-Lama, I have reviewed everything and added in some more comments. I think the title is perfect!

**Comment by Kalyan-Lama** [comment]
@exprin, I have updated your query. Could you go through it?

**Comment by exprin** [comment]
Sure, @Kalyan-Lama. Right away

**Comment by exprin** [comment]
@Kalyan-Lama, having reviewed this article, if you are done with the content you should be able to send it to Mae-Lin for the next step.

**Comment by Kalyan-Lama** [comment]
@maedelange would you mind going through the copy edits.

**Comment by maedelange** [comment]
@Kalyan-Lama I just finished my review and left some suggested edits/comments - feel free to let me know if you have any questions! :)

**Comment by Kalyan-Lama** [comment]
Thank you @maedelange for the thorough review. Will now start feeding the content to GitHub.

**Comment by Ig-Rebollo** [comment]
Looking great @Kalyan-Lama I left a few additional suggestions and comments, but overall is quite clear :)

**Comment by Kalyan-Lama** [comment]
Thank you, @Ig-Rebollo! I have accepted the suggestions and have also replied to your comments. Would you love to go through it before uploading it on GitHub?

**Comment by Ig-Rebollo** [comment]
Thank you @Kalyan-Lama and sorry for the delay! I added some suggestions on how to explain that piece further. I think it is otherwise ready to be published. Feel free to go ahead and create the PR for it once you've reviewed the suggestions!

**Comment by Kalyan-Lama** [comment]
Thank you, @Ig-Rebollo, for polishing the article. I will now work with the PR for the same.
