### ISSUE TITLE
New Article: Adding skip logic to a matrix question type

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#204]
Current the form builder does not allow a user to add skip logic to a matrix question type. The proposed article illustrates all the required steps on how the same can be achieved through an XLSForm.

**Comment by Kalyan-Lama** [comment]
Hi @exprin! Would you mind reviewing this new support article?

https://docs.google.com/document/d/157rCin0e9tma97ZYnm33MmDLccAFk19l/edit

**Comment by exprin** [comment]
Hi @Kalyan-Lama. Jumping on this right away

**Comment by exprin** [comment]
I have also added this in the "New Article List"

**Comment by Kalyan-Lama** [comment]
Great! Thank you!!!

**Comment by Kalyan-Lama** [comment]
Thank you for the quick review @exprin! I have made all the changes to the document as advised! 

@StephaneAloo @Ig-Rebollo, @joshuaberetta if you feel like having a quick look at the article, please feel free to go through it before we share it with Comms for the final copy edit.

**Comment by exprin** [comment]
@Kalyan-Lama, I have completed my review of this article. You should be able to move it to the next step with Mae-Lin

**Comment by maedelange** [comment]
@Kalyan-Lama I've gone through and left some comments/suggested edits- let me know if you have any questions! (Sorry if some of it is intuitive, I may just not have understood the technical aspect)
