### ISSUE TITLE
New Article: Adding calculations and constraints to a matrix question 

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#208]
The form builder approach does not permit a user to add calculations and constraints to a matrix question. This article thus aims to illustrate the following through the XLSForm:

* Adding calculations (row total) to a matrix question using the XLSForm
* Adding calculations (column total) to a matrix question using the XLSForm
* Adding constraints to a matrix question using the XLSForm

**Comment by Kalyan-Lama** [comment]
Hi @exprin, would you mind providing your comments and suggestion by reviewing the article?

https://docs.google.com/document/d/1qzGHFwXAKs578b0KXVQxAcr1dHSDziNw/edit

**Comment by exprin** [comment]
Not a problem @Kalyan-Lama .i will bee on it.

**Comment by exprin** [comment]
@Kalyan-Lama, great and very useful article! I have added my comments and suggestions, please check!

**Comment by Kalyan-Lama** [comment]
Thank you @exprin, for going through the article. I have some minor ones remaining. Would you mind going over it again?

**Comment by Kalyan-Lama** [comment]
@StephaneAloo, would you love to go through this article before pushing it to copy edit?

**Comment by Kalyan-Lama** [comment]
Thank you @StephaneAloo for the review and suggestions! @maedelange could you help me review the article?

**Comment by maedelange** [comment]
@Kalyan-Lama - wonderful article, I've left my edits/comments!

**Comment by Kalyan-Lama** [comment]
Thank you @maedelange!
