### ISSUE TITLE
Select one and select many question types

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#213]
This article describes the use of select one and select many question types, how to add them, and how they are displayed on Enketo and KoboCollect across multiple appearance types

https://docs.google.com/document/d/16B2T_0AxXlJd1hDHbBS7FyZCafkOb-hZEGWTcgDHUaE/edit?usp=sharing

**Comment by exprin** [comment]
Hi @Kalyan-Lama 
Kindly help me review this article.

**Comment by Kalyan-Lama** [comment]
Hi @exprin, I have finished reviewing the article. Please feel free to reach me back if needed.

**Comment by exprin** [comment]
Awesome! Thank you @Kalyan-Lama

**Comment by exprin** [comment]
@maedelange , @Ig-Rebollo kindly review this article for us

**Comment by maedelange** [comment]
@exprin - reviewed!
