### ISSUE TITLE
Pulling data from KoboToolbox to Excel and Power BI using Synchronous exports

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#217]
This article explains the process of connecting KoboToolbox projects to Power BI and Excel using the new Synchronous exports feature.

The suggestion is to have it replace [Pulling Data Into Excel Power Query](https://support.kobotoolbox.org/pulling_data_into_excelquery.html) and [Pulling data into PowerBI](https://support.kobotoolbox.org/pulling_data_into_powerbi.html)

Doc: https://docs.google.com/document/d/14P8isuBS9csCxJJ-lJ5enAmnHt7V2XSdzl8kHMx0O_k/edit#heading=h.6ashyfga7lju

**Comment by exprin** [comment]
@Ig-Rebollo, @joshuaberetta,
As in the discussion we had last Tuesday. I will go on and split this article into 2: "Pulling data from KoboToolbox to Microsoft Excel" and "Pulling data from KoboToolbox to PowerBI". This articles will then replace [Pulling Data Into Excel Power Query](https://support.kobotoolbox.org/pulling_data_into_excelquery.html) and [Pulling Data Into PowerBI](https://support.kobotoolbox.org/pulling_data_into_powerbi.html) respectively. 

Side note: I wish we could rearrange these articles in the side menu so they are close to each other

**Comment by exprin** [comment]
I have finished creating the 2 separate articles:
[- Connecting KoboToolbox with Excel
](https://docs.google.com/document/d/14P8isuBS9csCxJJ-lJ5enAmnHt7V2XSdzl8kHMx0O_k/edit#)
- [Connecting KoboToolbox with PowerBI](https://docs.google.com/document/d/1wWktFKlFWYahBfzACVLRbz4KLIgTdISsWt_UFBGF8nw/edit#heading=h.x4tpqiu4lra2)

**Comment by joshuaberetta** [comment]
@exprin I have reviewed the above articles. Please begin drafting the PRs when you have availability 🙂

**Comment by exprin** [comment]
Thank you @joshuaberetta. On it, now
