### ISSUE TITLE
Adding a Section (Minor Updates): Creating an account on KoboToolbox

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#218]
The current article is perfect but seems like we missed the following points which we could add as `Troubleshooting`:

## Troubleshooting:

1. Make sure to follow the bullets listed below to create a valid username:

   * The length of a username could range from 2 to 30 characters.
   * All the alphabets used in a username should be in lowercase. The use of uppercase alphabets would make the username invalid and the system should not accept such username.
   * A username could be combined with lowercase alphabets, numbers, and underscores. Use of other characters (such as `~`, `!`, `@`, `#`, `$`, `%`, `^`, `&`, `*`, `?`) are not accepted in a username. They can however be used in the password to make your password strong.
   * The first character of a username should always be an alphabet else the username should be invalid.

2. Sometimes you could be requested to choose another username (despite following all the checklist listed above) if the username you have applied for has already been registered within the system.

3. Ensure you don't have any typos in the registration form (with the `username` and `password`) else you may end up with a mismatch and the system may not allow you to login. Store your `username` and `password` in a safe place so that you don't lose them or someone else does not access them without your consent.

4. If you make a typo in the email you may not receive the activation link sent by the system. This is why you will need to re-verify the form once it has been filled out. *(e.g. if you typed a wrong email id say `example@gmai.com` or `exampl@gmail.com` you may not receive the activation link to your email id `example@gmail.com`)*

5. Make sure you change your `password` at a regular interval so that your account is safe and secure.

**Comment by exprin** [comment]
Sure I think this needs to go into the article. Please go ahead and edit it.

**Comment by Kalyan-Lama** [comment]
@exprin, I have planned to include this at the end of the article. Would you mind reviewing and polishing any content if you feel like it should? 

Link to the minor updates to the article: https://docs.google.com/document/d/1bhnkGuNQRrAyBrYfTXm9YApbH3JFnXFo/edit

**Comment by exprin** [comment]
@Kalyan-Lama I have added minor suggestions and a comment to the document. Please review
