### ISSUE TITLE
"Acknowledge" question type

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#220]
Continuing with the article series on question types, this article explains what the acknowledge question type is, when to use it, how to use it in skips and validations and more: https://docs.google.com/document/d/1C4uEtiDPo03AGNhkHhM8Mwf3i5v2MCdfzZ0TynddcHQ/edit?usp=sharing

**Comment by exprin** [comment]
@StephaneAloo, kindly help me with a review of this article

**Comment by Kalyan-Lama** [comment]
@exprin, reviewed this article! It's perfect!

**Comment by StephaneAloo** [comment]
@exprin this is now good to go

**Comment by exprin** [comment]
Thanks @StephaneAloo  and @Kalyan-Lama for the reviews

**Comment by exprin** [comment]
@maedelange  and @Ig-Rebollo could you please help me with come copy editing of this article?

**Comment by maedelange** [comment]
@exprin reviewed!
