### ISSUE TITLE
"Text" and "Note" question types

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#221]
This article describes the nature and usage of “Text” and “Note” question types including advanced appearances and other considerations. 

https://docs.google.com/document/d/17r4fj8_1UqF6P-NEcOoIoEqH5kcnqgIY3uZCokIdkVA/edit?usp=sharing

**Comment by exprin** [comment]
@StephaneAloo, kindly review this article for me.

**Comment by Kalyan-Lama** [comment]
@exprin, reviewed! I have added minor suggestions.

**Comment by exprin** [comment]
@Kalyan-Lama and @StephaneAloo . Thanks so much for the reviews. @Ig-Rebollo, @maedelange, kindly help me with review of the article

**Comment by maedelange** [comment]
@exprin reviewed!
