### ISSUE TITLE
Number, Decimal and Range question types

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#222]
This article describes the usage of Number, Decimal, and Range question types; including their advanced appearances.

https://docs.google.com/document/d/1VuWhGy_zQaP3GDZmza5Be7eiaIyoe2pJ3wf2rwQL6-I/edit?usp=sharing

**Comment by exprin** [comment]
@Kalyan-Lama, please help me review this article.

**Comment by Kalyan-Lama** [comment]
@exprin, I did go through it, and it's perfect!

**Comment by exprin** [comment]
Thank you so much @Kalyan-Lama!

**Comment by exprin** [comment]
@maedelange , @Ig-Rebollo kindly review this article for us!

**Comment by Ig-Rebollo** [comment]
Left some comments on this article. Let me know what you think @exprin @maedelange 

Feel free to go ahead and create a PR once comments/suggestions are resolved!

**Comment by maedelange** [comment]
@exprin @Ig-Rebollo - reviewed! I left some suggestions for number line ("sliding scale") and step ("increment")
