### ISSUE TITLE
Update contents: Is My Data Safe on Your Server?

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#231]
Update contents to an existing article **[Is My Data Safe on Your Server?](https://support.kobotoolbox.org/is_my_data_safe.html)** based on the conversation that has happened in **[Zulip](https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Is.20our.20AWS.20server.20encrypted.3F)**.

**Comment by joshuaberetta** [comment]
closed by #239
