### ISSUE TITLE
New article: Photo, audio, video and file question types

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#263]
https://docs.google.com/document/d/1tJ0NTbcwi7JaYODon5GmhDpwEmFq9kEZUdcLGvouDvk/edit#

**Comment by Ig-Rebollo** [comment]
Update from the call today:
- We will make the  section "Lowering the file size of collected media" a separate article to replace the [existing one](https://support.kobotoolbox.org/lower_file_size.html) on that topic.
- In this article, we will simply leave a quick mention with a link to the one dedicated to reducing the file size.

Also, a question: Is there a way to limit the file size for files other than images? For example, can I limit the size or the resolution of the audio or video? Maybe these are questions we could also address in the separate article.

**Comment by exprin** [comment]
@Ig-Rebollo here is the separate article: https://docs.google.com/document/d/1Ig2bHvaMa5vddunSCdM8KRDzNmKFOxq4mXpu8v4tmE4/edit#heading=h.k0fom23g5jmo

**Comment by Ig-Rebollo** [comment]
Thanks @exprin left some comments there, but looking great!

**Comment by Kalyan-Lama** [comment]
@exprin, I have left my suggestions to the article. Let me know if you are updating this article with the XLSForm approach. I may have some suggestions with the XLSForm approach too.

**Comment by exprin** [comment]
@Ig-Rebollo , @Kalyan-Lama, I have added sections explaining how to implement in XLSForm. Kindly review for me

**Comment by Kalyan-Lama** [comment]
@exprin, please see suggestions!

**Comment by exprin** [comment]
Thanks @Kalyan-Lama . On it

**Comment by Ig-Rebollo** [comment]
Again, looks great. Very minor suggestions from my end @exprin

**Comment by exprin** [comment]
Thank you @Ig-Rebollo
