### ISSUE TITLE
New article: Date and time question types

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#265]
https://docs.google.com/document/d/1hSn5oIAEZ1PtSn6ds8Q7y2N1riqK6Ws92iNwsr_mjLk/edit#

**Comment by exprin** [comment]
Thanks @Kalyan-Lama

**Comment by exprin** [comment]
@maedelange, please help review this article. cc @Ig-Rebollo

**Comment by maedelange** [comment]
@exprin reviewed!

**Comment by exprin** [comment]
@Kalyan-Lama, @maedelange thank you for your earlier reviews. I have also added sections on how to implement in XLSForm. could you kindly review it again?

**Comment by Kalyan-Lama** [comment]
It's superb @exprin!

**Comment by exprin** [comment]
Thanks a lot @Kalyan-Lama

**Comment by maedelange** [comment]
Looks great! Added a few minor suggestions @exprin

**Comment by exprin** [comment]
Thanks a lot, @maedelange. That was quick!

@Ig-Rebollo when you have time please do some final review and then I will do the markdown and send a PR

**Comment by Ig-Rebollo** [comment]
Made a couple very small suggestions, but otherwise looks good to go @exprin !

**Comment by exprin** [comment]
Thank you @Ig-Rebollo
