### ISSUE TITLE
Update article: Exporting and Downloading Your Data

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/docs#274]
The article on [exporting data](https://support.kobotoolbox.org/export_download.html) is now quite out of date.

**Comment by exprin** [comment]
@joshuaberetta we do have https://support.kobotoolbox.org/export_download.html

**Comment by joshuaberetta** [comment]
@exprin that's exactly the article this issue is noting needs updating 🙃

**Comment by exprin** [comment]
I was coming from your comment where you said "I don't think we have this article" and completely ignored the title of this issue. I will take a break and do the walk of shame, hahaha

**Comment by exprin** [comment]
@Kalyan-Lama, I have created this document here: https://docs.google.com/document/d/1SsnNoLCF_NJC2KSCii0bdrWlrVbkWN4xU_4hXdpW18g/edit#. Kindly review it

**Comment by Kalyan-Lama** [comment]
@exprin have reviewed the article. Looks great now!

**Comment by exprin** [comment]
Hi Kaylan,

Thank you so much. That's much appreciated

**Comment by exprin** [comment]
@maedelange, @Ig-Rebollo  kindly help out with your review of this article: https://docs.google.com/document/d/1SsnNoLCF_NJC2KSCii0bdrWlrVbkWN4xU_4hXdpW18g/edit#.

**Comment by maedelange** [comment]
Reviewed - looking good! @exprin
