### ISSUE TITLE
Managing permissions: Include how to remove shared projects

### ISSUE THREAD

**Issue by exprin** [kobotoolbox/docs#275]
https://support.kobotoolbox.org/managing_permissions.html

Doc: https://docs.google.com/document/d/1Phc6u7A0vHOZFaBMtB0zUxg4DVDyrAtaV5ugWShvOk0/edit#

**Comment by exprin** [comment]
Hi @Kalyan-Lama 
Kindly review the updates I have made to this article. 
I have added 2 sections: "Removing shared projects from your account" and "Makng your project public"
I have also updated the screenshots with GIFS

**Comment by Kalyan-Lama** [comment]
@exprin, great updates! I have completed the review and also made some suggestions!

**Comment by exprin** [comment]
Thank you for the review @Kalyan-Lama.

@Ig-Rebollo, @maedelange, kindly do a review of this article update.

**Comment by maedelange** [comment]
Reviewed @exprin!

**Comment by Ig-Rebollo** [comment]
Also made a revision and left some comments @exprin

**Comment by exprin** [comment]
@Ig-Rebollo, @joshuaberetta I have made changes to this article that require your review: https://docs.google.com/document/d/1Phc6u7A0vHOZFaBMtB0zUxg4DVDyrAtaV5ugWShvOk0/edit#. Kindly check it.
