### ISSUE TITLE
Update the contents of support article: Restricting Text Responses With Regular Expressions

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#311]
We have some minor content update requests for the support article (Restricting Text Responses With Regular Expressions) from the community forum (see details here):

https://community.kobotoolbox.org/t/request-for-edit-to-support-article-regex/29410 

Thus, with this request, the following contents shall also be updated (that has been frequently discussed in the community):

* Restricting an entry to 10, 13, or 17-digit numbers only (new content)

* Restricting an entry with accent characters (new content)

* Restricting time inputs (new content)

* Restricting a valid email id (update content)

* Restricting all texts to uppercase (new content)

* Restricting all texts to lowercase (new content)

* Restricting the first letter in uppercase (new content)

**Comment by nanometrenat** [comment]
@joshuaberetta what's the process to get the updates into the support article?  This one's been waiting a while, and the regex examples are still wrong in the docs.  Thanks a million!

**Comment by joshuaberetta** [comment]
Hi @nanometrenat, thanks for the prompt! I'll see about getting the PR merged now :)
