### ISSUE TITLE
مشكلة النقاط في جمع البيانات

### ISSUE THREAD

**Issue by moh1mmed** [kobotoolbox/docs#375]
عندما اقوم بجمع البيانات عن طريق كوبو كوليكت ميزة النقطة تستغرق زمن طويل ولا تفتح لا ادري لا تعمل معي؟
![Screenshot_٢٠٢٤-٠٨-٣١-١٢-٣٤-٥٧-٤٥٤_org koboc collect android](https://github.com/user-attachments/assets/87f6608d-869d-4213-b7b7-46b456537517)

**Comment by jnm** [comment]
Sorry, this is just a repository for updating documentation on https://support.kobotoolbox.org/.

If you need to troubleshoot a problem, please post your question in https://community.kobotoolbox.org/c/kobo-users/14. Thank you
