### ISSUE TITLE
Update support article "Collecting Data with KoBoCollect on Android"

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/docs#89]
Update support article with the updated images from the new version of `KoBoCollect android app`.

**Comment by Ig-Rebollo** [comment]
@Kalyan-Lama can you post here the link to the Google doc you are using for this article?

**Comment by Kalyan-Lama** [comment]
Sure @Ig-Rebollo. Will update it in the Google doc (and update the team) once I have drafted it at my end.

**Comment by Kalyan-Lama** [comment]
Here is the link to the article:

https://docs.google.com/document/d/1WtrdF0FYhlzzr-NN4aUui1SyK3QUj0eW/edit?usp=sharing&ouid=112352020379718229164&rtpof=true&sd=true
